### PR TITLE
update HalvingInterval

### PR DESCRIPTION
**Pull request by feathercoin2**
half every 2100000 blocks

### CODE REVIEW

**Comment by wrapperband** [comment]
What was the reasoning behind this change, was the halving blocks incorrectly specified?

**Comment by feathercoin2** [comment]
look 0.8.X  in main.cpp , I think it is an omission error.

**Comment by wrapperband** [comment]
yes, looks right,  from (Bush's) note
// Halving subsidy happens every 2,100,000 blocks. The code below takes account for the.
assume it must have been a typo, well spotted.

**Comment by wellenreiter01** [comment]
@ Lizhi, 
we also need a piece of code that takes care of the first halving due to the change from 2.5 mins to 1 min time frame for a block.
Did you copy the corresponding code from 0.8.7, too?

**Pull request merged**
